version: "3.8"
services:
    mongodb:
        image: 'mongo'
        volumes:
            - data:/data/db
        container_name: 'mongodb-container'
    backend:
        build: ./backend
        ports:
            - '80:80'
        container_name: 'backend-container'
        depends_on:
            - mongodb
volumes:
    data: