# version: "3.8"
# services:
#     mongodb:
#         image: 'mongo'
#         volumes:
#             - data:/data/db
#         container_name: 'mongodb-container-prod'
#     backend:
#         build: ./../backend
#         ports:
#             - '80:80'
#         container_name: 'backend-container-prod'
#         depends_on:
#             - mongodb
#     frontend:
#         build: ./../frontend
#         ports:
#             - 3000:3000
#         container_name: 'frontend-container-prod'
#         stdin_open: true
#         tty: true
#         depends_on: 
#             - backend
# volumes:
#     data: